version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt-get update
      - apt-get install -y jq
      - apt-get -y install wget
      - apt-get -y install default-jdk
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
      - mkdir zap
      - tar -xvf ZAP_2.11.1_Linux.tar.gz
      - cd ZAP_2.11.1
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html  
  pre_build:
    commands:
       - echo Nothing to do in the pre_build phase...
  build:
    commands:
     - echo Build started on `date`
      - mvn install
    paths:
      - "node_modules/**/*"
artifacts:
  files:
      - zap_report.html